//= error exception

fun main() {
  do {
    foo();
  } catch x: Str {
    println(x);
  }
}

fun foo() {
  throw "catch me";
}
