//= "caught\nException\n0: main(): 5\nafter\nend\n"

fun main() {
  do {
    try throwFromNative(true);
    assert(false);
  } catch e: Exception {
    println("caught");
    e.printStackTrace();
    assert(true);
  }

  println("after");
  try! throwFromNative(false);
  println("end");
}
