//= error exception

fn main() {
  throw "error";
}
